//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RogueSharper.BrowseToReflector.Reflector {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Reflector.IReflectorBrowseService")]
    public interface IReflectorBrowseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectorBrowseService/Ping", ReplyAction="http://tempuri.org/IReflectorBrowseService/PingResponse")]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReflectorBrowseService/Browse", ReplyAction="http://tempuri.org/IReflectorBrowseService/BrowseResponse")]
        void Browse(string assembly, string type, string member);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IReflectorBrowseServiceChannel : RogueSharper.BrowseToReflector.Reflector.IReflectorBrowseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReflectorBrowseServiceClient : System.ServiceModel.ClientBase<RogueSharper.BrowseToReflector.Reflector.IReflectorBrowseService>, RogueSharper.BrowseToReflector.Reflector.IReflectorBrowseService {
        
        public ReflectorBrowseServiceClient() {
        }
        
        public ReflectorBrowseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReflectorBrowseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReflectorBrowseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReflectorBrowseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Ping() {
            base.Channel.Ping();
        }
        
        public void Browse(string assembly, string type, string member) {
            base.Channel.Browse(assembly, type, member);
        }
    }
}
